# Generated by Django 4.1 on 2022-10-17 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cota',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=140)),
                ('administradora', models.CharField(max_length=140)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=20)),
                ('entrada', models.DecimalField(decimal_places=2, max_digits=20)),
                ('segmento', models.CharField(max_length=140)),
                ('vencimento', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Parcelas',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('qt_parcelas', models.IntegerField()),
                ('valor_parcelas', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cota_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcelas', to='cotas.cota')),
            ],
        ),
    ]
