# Generated by Django 4.1 on 2022-08-30 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administradora',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=140)),
                ('img', models.ImageField(null=True, upload_to='cotas/static/cotas/images', verbose_name='Logo Administradora')),
            ],
        ),
        migrations.CreateModel(
            name='Cota',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=140)),
                ('administradora', models.CharField(max_length=140)),
                ('valor', models.FloatField()),
                ('entrada', models.FloatField()),
                ('parcelas', models.IntegerField()),
                ('segmento', models.ImageField(null=True, upload_to='loja/static/loja/images', verbose_name='Product Image')),
                ('vencimento', models.TextField()),
                ('img', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cotas.administradora')),
            ],
        ),
    ]
