# Generated by Django 4.1 on 2022-10-24 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cotas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagem',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('img', models.ImageField(null=True, upload_to='cotas/static/images', verbose_name='Arte')),
                ('cota_cod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cotas.cota')),
            ],
        ),
    ]
