# Generated by Django 4.1 on 2022-08-30 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cota',
            name='img',
            field=models.CharField(max_length=255),
        ),
    ]
