# Generated by Django 4.1 on 2022-10-24 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotas', '0002_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagem',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
