# Generated by Django 4.1.2 on 2022-10-15 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cotas', '0003_alter_cota_entrada_alter_cota_parcelas_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cota',
            name='parcelas',
        ),
        migrations.CreateModel(
            name='Parcelas',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('qt_parcelas', models.IntegerField()),
                ('valor_parcelas', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cota_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cotas.cota')),
            ],
        ),
    ]
