# Generated by Django 4.1.2 on 2022-10-16 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cotas', '0004_remove_cota_parcelas_parcelas'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Administradora',
        ),
        migrations.RemoveField(
            model_name='cota',
            name='img',
        ),
        migrations.AlterField(
            model_name='parcelas',
            name='cota_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcelas', to='cotas.cota'),
        ),
    ]
